# Este es el archivo de configuración de Codemagic YAML para aplicaciones Flutter.
# Puedes encontrar más información en la documentación oficial:
# https://docs.codemagic.io/getting-started/codemagic-yaml/

# 1. Define tu flujo de trabajo
workflows:
  android-build:
    name: Build Android App
    # 2. Configura los disparadores de compilación (cuando se ejecuta el flujo)
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true

    # 3. Define la máquina de compilación
    instance_type: mac_mini_m1
    
    # 4. Define los scripts de compilación
    environment:
      flutter: stable

    scripts:
      - name: Configurar y Compilar
        script: |
          # Cambia a la carpeta de tu proyecto.
          # Reemplaza 'nombre_de_tu_carpeta' con el nombre de tu proyecto.
          cd shoijet
          
      

          # Instala las dependencias del proyecto.
          flutter packages get
          
          # Compila la aplicación Android.
          flutter build apk --release

    # 5. Define dónde guardar los artefactos (el archivo .apk)
    artifacts:
      # Asegúrate de que este path sea correcto desde la raíz del repositorio.
      - shoijet/app/build/outputs/flutter-apk/app-release.apk
