# Este es un archivo de configuración de Codemagic YAML para aplicaciones Flutter.
# Puedes encontrar más información en la documentación oficial:
# https://docs.codemagic.io/getting-started/codemagic-yaml/

# 1. Define tu flujo de trabajo
workflows:
  android-build:
    name: Build Android App
    # 2. Configura los disparadores de compilación (cuando se ejecuta el flujo)
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true

    # 3. Define la máquina de compilación
    # Este es el tipo de instancia corregido.
    # linux_x2_medium ya no es un tipo de instancia válido.
    instance_type: mac_mini_m1
    
    # 4. Define los scripts de compilación
    environment:
      flutter: stable
      # Si necesitas variables de entorno (por ejemplo, para claves API), las puedes definir aquí
      # vars:
      #   API_KEY: "tu_api_key_aqui"

    scripts:
      - name: Instalar dependencias de Flutter
        script: |
          flutter packages get
      
      - name: Compilar la aplicación Android
        script: |
          # El comando para compilar la versión de lanzamiento de Android
          flutter build apk --release

    # 5. Define dónde guardar los artefactos (el archivo .apk)
    artifacts:
      - app/build/outputs/flutter-apk/app-release.apk

    # 6. Define lo que quieres que pase después de la compilación
    publishing:
      # Publicar en Firebase App Distribution (opcional)
      # firebase:
      #   # Puedes dejar el token vacío si lo tienes como una variable de entorno en Codemagic
      #   firebase_app_distrib:
      #     appId: 1:01234567890:android:abcdefgh
      #     groups: "testers"
      #     token: "tu_token_aqui"
