# Este es el archivo de configuración de Codemagic YAML para aplicaciones Flutter.
# Puedes encontrar más información en la documentación oficial:
# https://docs.codemagic.io/getting-started/codemagic-yaml/

# 1. Define tu flujo de trabajo
workflows:
  android-build:
    name: Build Android App
    # 2. Configura los disparadores de compilación (cuando se ejecuta el flujo)
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true

    # 3. Define la máquina de compilación
    # mac_mini_m1 es la instancia recomendada para proyectos de Flutter.
    instance_type: mac_mini_m1
    
    # 4. Define los scripts de compilación
    environment:
      flutter: stable
      # Si necesitas variables de entorno (por ejemplo, para claves API), las puedes definir aquí
      # vars:
      #   API_KEY: "tu_api_key_aqui"

    scripts:
      - name: Configurar Flutter
        script: |
          # Este paso le dice a Codemagic que configure el SDK de Flutter.
          flutter sdk-path | xargs flutter_tools

      - name: Instalar dependencias de Flutter
        script: |
          # Ahora, este comando funcionará sin problemas
          flutter packages get
      
      - name: Compilar la aplicación Android
        script: |
          # El comando para compilar la versión de lanzamiento de Android
          flutter build apk --release

    # 5. Define dónde guardar los artefactos (el archivo .apk)
    artifacts:
      - app/build/outputs/flutter-apk/app-release.apk

# La sección 'publishing' fue eliminada para evitar errores
# ya que no es necesaria para una compilación básica.
